version: "3"
services: 

    mymongo_1:
        image: "mongo"
        ports:
          - "500:27017"

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        cap_add:
          - SYS_NICE
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER_PASSWORD: root
          MYSQL_USER: root
        volumes:
          - ./mysql-data:/var/lib/mysql
          - ./mysql-init-files:/docker-entrypoint-initdb.d
        ports:
          - "3306:3306"

    # db:
    #   image: mysql:5.7
    #   ports:
    #     - "3306:3306"
    #   environment:
    #     MYSQL_PASSWORD: roote
    #     MYSQL_USER: roote
    #     MYSQL_DATABASE: test
    #   volumes:
    #     - ./dump.sql:/docker-entrypoint-initdb.d/test.sql


    
    myreader:
        build: .
        depends_on: 
            - mymongo_1
        ports:
            - "5001:5001"

volumes: # Relevantno
  mysql-data: