-- Adminer 4.7.7 MySQL dump
-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 17:26:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



CREATE DATABASE `ChargerDatabase` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `ChargerDatabase`;

-- -----------------------------------------------------
-- Table `mydb`.`SiteData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargerDatabase`.`SiteData`;
CREATE TABLE `ChargerDatabase`.`SiteData` (
  `AGENT_CODE` varchar(6) NOT NULL DEFAULT '',
  `AGENT_NAME` varchar(40) DEFAULT NULL,
  `WORKING_AREA` varchar(35) DEFAULT NULL,
  `COMMISSION` decimal(10,2) DEFAULT NULL,
  `PHONE_NO` varchar(15) DEFAULT NULL,
  `COUNTRY` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`AGENT_CODE`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `SiteData` (`AGENT_CODE`, `AGENT_NAME`, `WORKING_AREA`, `COMMISSION`, `PHONE_NO`, `COUNTRY`) VALUES
('A007  ', 'Ramasundar                              ', 'Bangalore                          ', '0.15', '077-25814763   ', '\r'),
('A003  ', 'Alex                                    ', 'London                             ', '0.13', '075-12458969   ', '\r'),
('A008  ', 'Alford                                  ', 'New York                           ', '0.12', '044-25874365   ', '\r'),
('A011  ', 'Ravi Kumar                              ', 'Bangalore                          ', '0.15', '077-45625874   ', '\r'),
('A010  ', 'Santakumar                              ', 'Chennai                            ', '0.14', '007-22388644   ', '\r'),
('A012  ', 'Lucida                                  ', 'San Jose                           ', '0.12', '044-52981425   ', '\r'),
('A005  ', 'Anderson                                ', 'Brisban                            ', '0.13', '045-21447739   ', '\r'),
('A001  ', 'Subbarao                                ', 'Bangalore                          ', '0.14', '077-12346674   ', '\r'),
('A002  ', 'Mukesh                                  ', 'Mumbai                             ', '0.11', '029-12358964   ', '\r'),
('A006  ', 'McDen                                   ', 'London                             ', '0.15', '078-22255588   ', '\r'),
('A004  ', 'Ivan                                    ', 'Torento                            ', '0.15', '008-22544166   ', '\r'),
('A009  ', 'Benjamin                                ', 'Hampshair                          ', '0.11', '008-22536178   ', '\r');
-- -----------------------------------------------------
-- Table `mydb`.`StationData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargerDatabase`.`StationData`;
CREATE TABLE `ChargerDatabase`.`StationData` (
  `stationId` INT NOT NULL AUTO_INCREMENT,
  `site_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `lastUpdated` DATETIME NULL,
  `adress` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`stationId`),
  INDEX `siteId_idx` (`site_id` ASC) VISIBLE,
  CONSTRAINT `siteIdFK`
    FOREIGN KEY (`site_id`)
    REFERENCES `ChargerDatabase`.`SiteData` (`siteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `mydb`.`OutletData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ChargerDatabase`.`OutletData`;
CREATE TABLE `ChargerDatabase`.`OutletData` (
  `outletId` INT NOT NULL AUTO_INCREMENT,
  `connector` INT NULL,
  `kilowatts` FLOAT NULL,
  `power` FLOAT NULL,
  `type` VARCHAR(100) NULL,
  PRIMARY KEY (`outletId`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `ChargerDatabase`.`ChargerData`;
CREATE TABLE `ChargerDatabase`.`ChargerData` (
  `chargerId` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(100) NOT NULL,
  `longitude` VARCHAR(100) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `name` VARCHAR(100) NULL,
  `stationId` INT NULL,
  `outletId` INT NULL,
  PRIMARY KEY (`chargerId`),
  INDEX `stationId_idx` (`stationId` ASC) VISIBLE,
  INDEX `outletId_idx` (`outletId` ASC) VISIBLE,
  CONSTRAINT `stationIdFK`
    FOREIGN KEY (`stationId`)
    REFERENCES `ChargerDatabase`.`StationData` (`stationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `outletIdFK`
    FOREIGN KEY (`outletId`)
    REFERENCES `ChargerDatabase`.`OutletData` (`outletId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));